#!/usr/bin/env node

const rt = require('raml-tester');
const params = process.argv.slice(2);
if (params[0] === 'stop') {
    const port = params.length > 1 ? parseInt(params[1]) : 8090;
    rt.stop(port);
    console.log('Proxy stopped');
} else {
    rt.isSameParams(params, function (isSame) {
        if (isSame) {
            console.log('Reloading proxy');
            rt.reload(rt.findPort(params));
        } else {
            console.log('Starting proxy...');
            rt.start(params, function (ok) {
                if (!ok) {
                    console.log('Stop waiting for proxy');
                }
            });
        }
    });
}